[package]
name = "ocypode"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hyper = "1.1.0"
tokio = { version = "1.36.0", features = ["full"] }
serde = "1.0.196"
serde_json = "1.0.113"